package kr.co.TRSolution.trsIbp.resource.web;
import javax.annotation.Resource; import javax.servlet.http.HttpServletRequest; import org.springframework.stereotype.Controller; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.ModelAndView;
import kr.co.TRSolution.trsIbp.authority.service.AuthorityService; import kr.co.TRSolution.trsIbp.resource.service.ResourceService; import kr.co.TRSolution.trsIbp.resource.vo.ResourceVO; import kr.co.TRSolution.trsIbp.user.vo.UserVO;
@Controller public class ResourceController {
 @Resource(name="resourceService") private ResourceService service; @Resource(name="authorityService") private AuthorityService authorityService;
 @RequestMapping("/resource/reservationList.do") public String reservationPage(){return "/resource/reservationList";} @RequestMapping("/resource/resourceManage.do") public String managePage(){return "/resource/resourceManage";}
 @RequestMapping("/resource/resourceList.ajax") public ModelAndView resources(ResourceVO vo,HttpServletRequest req){UserVO u=init(vo,req); ModelAndView m=json();m.addObject("list",service.selectResourceList(vo));m.addObject("bizList",service.selectAvailableBizList(vo));m.addObject("companyScopeYn",authorityService.isCompanyDataScope(u)?"Y":"N");m.addObject("result","OK");return m;}
 @RequestMapping(value="/resource/resourceSave.ajax",method=RequestMethod.POST) public ModelAndView resourceSave(ResourceVO vo,HttpServletRequest req){ModelAndView m=json();try{UserVO u=init(vo,req);vo.setRgtrId(u.getUserId());vo.setMdfrId(u.getUserId());service.saveResource(vo);m.addObject("result","OK");m.addObject("resourceSn",vo.getResourceSn());}catch(Exception e){m.addObject("result","FAIL");m.addObject("msg",e.getMessage());}return m;}
 @RequestMapping(value="/resource/resourceDelete.ajax",method=RequestMethod.POST) public ModelAndView resourceDelete(ResourceVO vo,HttpServletRequest req){ModelAndView m=json();try{UserVO u=init(vo,req);vo.setMdfrId(u.getUserId());service.deleteResource(vo);m.addObject("result","OK");}catch(Exception e){m.addObject("result","FAIL");m.addObject("msg",e.getMessage());}return m;}
 @RequestMapping("/resource/reservationList.ajax") public ModelAndView reservations(ResourceVO vo,HttpServletRequest req){init(vo,req);ModelAndView m=json();m.addObject("list",service.selectReservationList(vo));m.addObject("result","OK");return m;}
 @RequestMapping(value="/resource/reservationSave.ajax",method=RequestMethod.POST) public ModelAndView reservationSave(ResourceVO vo,HttpServletRequest req){ModelAndView m=json();try{UserVO u=init(vo,req);vo.setUserId(u.getUserId());vo.setRgtrId(u.getUserId());vo.setMdfrId(u.getUserId());service.saveReservation(vo);m.addObject("result","OK");m.addObject("reservationSn",vo.getReservationSn());}catch(Exception e){m.addObject("result","FAIL");m.addObject("msg",e.getMessage());}return m;}
 @RequestMapping(value="/resource/reservationDelete.ajax",method=RequestMethod.POST) public ModelAndView reservationDelete(ResourceVO vo,HttpServletRequest req){ModelAndView m=json();try{UserVO u=init(vo,req);vo.setUserId(u.getUserId());vo.setMdfrId(u.getUserId());service.deleteReservation(vo);m.addObject("result","OK");}catch(Exception e){m.addObject("result","FAIL");m.addObject("msg",e.getMessage());}return m;}
 private UserVO init(ResourceVO vo,HttpServletRequest req){UserVO u=(UserVO)req.getSession().getAttribute("login");if(u==null)throw new IllegalStateException("로그인이 필요합니다.");vo.setCoId(u.getCoId());vo.setUserId(u.getUserId());vo.setCompanyScopeYn(authorityService.isCompanyDataScope(u)?"Y":"N");return u;} private ModelAndView json(){return new ModelAndView("jsonView");}
}
