package kr.co.TRSolution.trsIbp.expense.web;
import java.util.*; import javax.annotation.Resource; import javax.servlet.http.HttpServletRequest; import org.springframework.stereotype.Controller; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.servlet.ModelAndView;
import kr.co.TRSolution.trsIbp.authority.service.AuthorityService; import kr.co.TRSolution.trsIbp.comm.file.mapper.CommonFileMapper; import kr.co.TRSolution.trsIbp.comm.file.vo.CommonFileVO; import kr.co.TRSolution.trsIbp.expense.service.ExpenseService; import kr.co.TRSolution.trsIbp.expense.vo.ExpenseVO; import kr.co.TRSolution.trsIbp.user.vo.UserVO;
@Controller public class ExpenseController {
 @Resource(name="expenseService") private ExpenseService service; @Resource(name="authorityService") private AuthorityService authorityService; @Resource(name="commonFileMapper") private CommonFileMapper fileMapper;
 @RequestMapping("/expense/expenseList.do") public String page(){return "/expense/expenseList";}
 @RequestMapping("/expense/expenseList.ajax") public ModelAndView list(ExpenseVO vo,HttpServletRequest req){UserVO u=login(req);vo.setCoId(u.getCoId());vo.setUserId(u.getUserId());vo.setCompanyScopeYn(authorityService.isCompanyDataScope(u)?"Y":"N");ModelAndView m=json();m.addObject("list",service.selectExpenseList(vo));m.addObject("bizList",service.selectAvailableBizList(vo));m.addObject("result","OK");return m;}
 @RequestMapping("/expense/expenseDetail.ajax") public ModelAndView detail(ExpenseVO vo,HttpServletRequest req){UserVO u=login(req);vo.setCoId(u.getCoId());vo.setUserId(u.getUserId());vo.setCompanyScopeYn(authorityService.isCompanyDataScope(u)?"Y":"N");ModelAndView m=json();m.addObject("detail",service.selectExpense(vo));m.addObject("result","OK");return m;}
 @RequestMapping(value="/expense/expenseSave.ajax",method=RequestMethod.POST) public ModelAndView save(ExpenseVO vo,@RequestParam(value="files",required=false) MultipartFile[] files,HttpServletRequest req){ModelAndView m=json();try{UserVO u=login(req);vo.setCoId(u.getCoId());vo.setUserId(u.getUserId());vo.setRgtrId(u.getUserId());vo.setMdfrId(u.getUserId());vo.setCompanyScopeYn(authorityService.isCompanyDataScope(u)?"Y":"N");service.saveExpense(vo,files);m.addObject("result","OK");m.addObject("claimSn",vo.getClaimSn());}catch(Exception e){m.addObject("result","FAIL");m.addObject("msg",e.getMessage());}return m;}
 @RequestMapping(value="/expense/expenseDelete.ajax",method=RequestMethod.POST) public ModelAndView delete(ExpenseVO vo,HttpServletRequest req){ModelAndView m=json();try{UserVO u=login(req);vo.setCoId(u.getCoId());vo.setUserId(u.getUserId());vo.setMdfrId(u.getUserId());vo.setCompanyScopeYn(authorityService.isCompanyDataScope(u)?"Y":"N");service.deleteExpense(vo);m.addObject("result","OK");}catch(Exception e){m.addObject("result","FAIL");m.addObject("msg",e.getMessage());}return m;}
 @RequestMapping("/expense/expenseFiles.ajax") public ModelAndView files(@RequestParam("claimSn") Long sn,HttpServletRequest req)throws Exception{UserVO u=login(req);CommonFileVO f=new CommonFileVO();f.setCoId(u.getCoId());f.setRefSeCd("EXPENSE_CLAIM");f.setRefId(String.valueOf(sn));f.setFileSeCd("RECEIPT");ModelAndView m=json();m.addObject("list",fileMapper.selectFileList(f));m.addObject("result","OK");return m;}
 private UserVO login(HttpServletRequest r){UserVO u=(UserVO)r.getSession().getAttribute("login");if(u==null)throw new IllegalStateException("로그인이 필요합니다.");return u;} private ModelAndView json(){return new ModelAndView("jsonView");}
}
