var expenseRows=[],expenseBiz=[];
function e(v){return $('<div>').text(v==null?'':v).html()}
function amt(v){return Number(v||0).toLocaleString('ko-KR')+'원'}
function expType(c){return {LODGING:'숙박',SUPPLY:'물품',MEAL:'식비',TRANSPORT:'교통',FUEL:'유류',ETC:'기타'}[c]||c||'-'}
function payText(x){var n={PERSONAL_CARD:'개인카드',CORP_CARD:'법인카드',CASH:'현금',ETC:'기타'}[x.pmtMthdCd]||x.pmtMthdCd||'-';return x.cardLast4&&(x.pmtMthdCd==='PERSONAL_CARD'||x.pmtMthdCd==='CORP_CARD')?n+' · **** '+x.cardLast4:n}
function toggleCardLast4(){var card=$('#expPay').val()==='PERSONAL_CARD'||$('#expPay').val()==='CORP_CARD';$('#expCardLast4Field').toggleClass('hidden',!card);$('#expCardLast4').prop('required',card);if(!card)$('#expCardLast4').val('')}
function loadExpenses(){$.getJSON(ctxPath+'/expense/expenseList.ajax',{searchKeyword:$('#expenseSearch').val()},function(r){expenseRows=r.list||[];expenseBiz=r.bizList||[];$('#expBizId').html('<option value="">선택</option>'+expenseBiz.map(function(x){return '<option value="'+e(x.bizId)+'">'+e(x.bizAbrvNm||x.bizNm)+'</option>'}).join(''));$('#expenseBody').html(expenseRows.length?expenseRows.map(function(x){return '<tr><td>'+e(x.useYmd)+'</td><td>'+e(x.bizAbrvNm||x.bizNm)+'</td><td>'+e(expType(x.expnsSeCd))+'<br><small class="text-gray-500">'+e(payText(x))+'</small></td><td>'+e(x.expnsNm)+'</td><td>'+e(x.merchantNm||'-')+'</td><td class="text-right font-bold">'+amt(x.claimAmt)+'</td><td>'+e(x.userNm||x.userId)+'</td><td><button class="ds-btn ds-btn-outline" onclick="event.stopPropagation();showFiles('+x.claimSn+')">보기</button></td><td><button class="ds-btn ds-btn-outline" onclick="openExpenseForm('+x.claimSn+')">수정</button> <button class="ds-btn ds-btn-outline" onclick="deleteExpense('+x.claimSn+')">삭제</button></td></tr>'}).join(''):'<tr><td colspan="9" class="ds-empty">등록된 비용청구가 없습니다.</td></tr>')})}
function openExpenseForm(sn){document.getElementById('expenseForm').reset();$('#claimSn').val('');$('#expenseExistingFiles').empty();if(sn){var x=expenseRows.filter(function(v){return String(v.claimSn)===String(sn)})[0];if(x){$('#claimSn').val(x.claimSn);$('#expBizId').val(x.bizId);$('#expUseYmd').val(x.useYmd);$('#expSe').val(x.expnsSeCd);$('#expPay').val(x.pmtMthdCd);$('#expCardLast4').val(x.cardLast4||'');$('#expAmt').val(x.claimAmt);$('#expNm').val(x.expnsNm);$('#expMerchant').val(x.merchantNm);$('#expRmrk').val(window.decodeStoredText?window.decodeStoredText(x.rmrkCn||''):(x.rmrkCn||''));showFiles(sn,'#expenseExistingFiles')}}else $('#expUseYmd').val(new Date().toISOString().slice(0,10));toggleCardLast4();$('#expenseModal').removeClass('hidden')}
function closeExpenseForm(){$('#expenseModal').addClass('hidden')}
function showFiles(sn,target){target=target||null;$.getJSON(ctxPath+'/expense/expenseFiles.ajax',{claimSn:sn},function(r){var h=(r.list||[]).map(function(f){return '<a class="text-cyan-300 mr-3" target="_blank" href="'+ctxPath+'/common/fileView.do?atchFileSn='+f.atchFileSn+'">'+e(f.orgnlFileNm)+'</a>'}).join('')||'<span class="text-gray-500">첨부 없음</span>';if(target)$(target).html(h);else alert((r.list||[]).map(function(f){return f.orgnlFileNm}).join('\n')||'첨부파일이 없습니다.')})}
$('#expPay').on('change',toggleCardLast4);$('#expCardLast4').on('input',function(){this.value=this.value.replace(/\D/g,'').slice(0,4)});
$('#expenseForm').on('submit',function(ev){ev.preventDefault();toggleCardLast4();if($('#expCardLast4').prop('required')&&!/^\d{4}$/.test($('#expCardLast4').val()))return alert('카드 뒷번호 4자리를 입력해 주세요.');var fd=new FormData(this);$.ajax({url:ctxPath+'/expense/expenseSave.ajax',type:'POST',data:fd,processData:false,contentType:false,dataType:'json',success:function(r){if(r.result==='OK'){closeExpenseForm();loadExpenses()}else alert(r.msg||'저장 실패')}})});
function deleteExpense(sn){if(!confirm('삭제하면 프로젝트 비용에서도 즉시 제외됩니다. 삭제하시겠습니까?'))return;$.post(ctxPath+'/expense/expenseDelete.ajax',{claimSn:sn},function(r){if(r.result==='OK')loadExpenses();else alert(r.msg||'삭제 실패')},'json')}
$(function(){toggleCardLast4();loadExpenses()});
