function rawText(v){return window.decodeStoredText?window.decodeStoredText(v==null?'':v):(v==null?'':String(v));}
function esc(v){return $('<div>').text(rawText(v)).html();}
var resources=[], reservations=[], bizList=[];
function api(url,data,ok){$.ajax({url:ctxPath+url,type:'POST',data:data||{},dataType:'json',success:function(r){if(r.result==='OK')ok(r);else alert(r.msg||'처리 중 오류가 발생했습니다.');},error:function(){alert('요청 처리 중 오류가 발생했습니다.');}});}
function initResourceManage(){renderResourceAttrRows([]);loadResources(true);}
function initReservationPage(){loadResources(false);}
function loadResources(manage){api('/resource/resourceList.ajax',{},function(r){resources=r.list||[];bizList=r.bizList||[]; if(manage){renderResources();}else{renderReservationSelects();loadReservations();}});}
function typeNm(v){return {MEETING_ROOM:'회의실',VEHICLE:'차량',IT_DEVICE:'IT장비',SERVER:'서버',ETC:'기타'}[v]||v;}
function modeNm(v){return {TIME:'시간예약',LOAN:'대여',ASSIGN:'할당'}[v]||v;}
function renderResources(){var h='';$.each(resources,function(_,r){h+='<tr><td>'+esc(r.resourceNm)+'</td><td>'+esc(typeNm(r.resourceTypeCd))+'</td><td>'+esc(r.locationNm)+'</td><td>'+esc(modeNm(r.useModeCd))+'</td><td>'+(r.bookableYn==='Y'?'가능':'불가')+'</td><td><pre class="whitespace-pre-wrap text-xs">'+esc(r.attrText)+'</pre></td><td><button class="ds-mini-btn" onclick="editResource('+r.resourceSn+')">수정</button> <button class="ds-mini-btn ds-mini-btn-danger" onclick="deleteResource('+r.resourceSn+')">삭제</button></td></tr>';});$('#resourceBody').html(h||'<tr><td colspan="7" class="ds-empty">등록된 자원이 없습니다.</td></tr>');}
function parseResourceAttrs(text){var rows=[];String(rawText(text||'')).split(/\r?\n/).forEach(function(line){if(!line.trim())return;var p=line.indexOf('=');if(p<1)return;rows.push({name:line.substring(0,p).trim(),value:line.substring(p+1).trim()});});return rows;}
function renderResourceAttrRows(rows){rows=rows&&rows.length?rows:[{name:'',value:''}];$('#resourceAttrBody').html(rows.map(function(a){return '<tr><td><input type="text" class="ds-input resource-attr-name" maxlength="100" value="'+esc(a.name||'')+'" placeholder="예: IP, 수용인원, 차량번호"></td><td><input type="text" class="ds-input resource-attr-value" maxlength="500" value="'+esc(a.value||'')+'" placeholder="항목값 입력"></td><td><button type="button" class="ds-mini-btn ds-mini-btn-danger" onclick="removeResourceAttrRow(this)">삭제</button></td></tr>';}).join(''));}
function addResourceAttrRow(){var row='<tr><td><input type="text" class="ds-input resource-attr-name" maxlength="100" placeholder="예: IP, 수용인원, 차량번호"></td><td><input type="text" class="ds-input resource-attr-value" maxlength="500" placeholder="항목값 입력"></td><td><button type="button" class="ds-mini-btn ds-mini-btn-danger" onclick="removeResourceAttrRow(this)">삭제</button></td></tr>';$('#resourceAttrBody').append(row);$('#resourceAttrBody tr:last .resource-attr-name').focus();}
function removeResourceAttrRow(btn){$(btn).closest('tr').remove();if(!$('#resourceAttrBody tr').length)renderResourceAttrRows([]);}
function collectResourceAttrText(){var lines=[],invalid=false;$('#resourceAttrBody tr').each(function(){var n=$(this).find('.resource-attr-name').val().trim();var v=$(this).find('.resource-attr-value').val().trim();if(!n&&!v)return;if(!n){invalid=true;return false;}lines.push(n+'='+v);});if(invalid){alert('부가정보의 항목명을 입력하십시오.');return null;}return lines.join('\n');}
function editResource(sn){var r=resources.find(function(x){return String(x.resourceSn)===String(sn);});if(!r)return;$('#resourceSn').val(r.resourceSn);$('#resourceNm').val(rawText(r.resourceNm));$('#resourceType').val(r.resourceTypeCd);$('#useMode').val(r.useModeCd);$('#bookableYn').val(r.bookableYn);$('#locationNm').val(rawText(r.locationNm));$('#resourceExpln').val(rawText(r.resourceExpln));renderResourceAttrRows(parseResourceAttrs(r.attrText));window.scrollTo({top:0,behavior:'smooth'});}
function resetResourceForm(){$('#resourceSn,#resourceNm,#locationNm,#resourceExpln').val('');$('#resourceType').val('MEETING_ROOM');$('#useMode').val('TIME');$('#bookableYn').val('Y');renderResourceAttrRows([]);}
function saveResource(){if(!$('#resourceNm').val().trim())return alert('자원명을 입력하십시오.');var attrText=collectResourceAttrText();if(attrText===null)return;api('/resource/resourceSave.ajax',{resourceSn:$('#resourceSn').val(),resourceNm:$('#resourceNm').val(),resourceTypeCd:$('#resourceType').val(),useModeCd:$('#useMode').val(),bookableYn:$('#bookableYn').val(),locationNm:$('#locationNm').val(),resourceExpln:$('#resourceExpln').val(),attrText:attrText},function(){resetResourceForm();loadResources(true);});}
function deleteResource(sn){if(!confirm('자원을 삭제하시겠습니까?'))return;api('/resource/resourceDelete.ajax',{resourceSn:sn},function(){resetResourceForm();loadResources(true);});}
function renderReservationSelects(){var h='<option value="">자원 선택</option>';$.each(resources,function(_,r){if(r.bookableYn==='Y')h+='<option value="'+r.resourceSn+'">'+esc('['+typeNm(r.resourceTypeCd)+'] '+r.resourceNm+(r.locationNm?' / '+r.locationNm:''))+'</option>';});$('#rsvResource').html(h);h='<option value="">프로젝트 없음</option>';$.each(bizList,function(_,b){h+='<option value="'+esc(b.bizId)+'">'+esc(b.bizNm)+'</option>';});$('#rsvBiz').html(h);}
function loadReservations(){api('/resource/reservationList.ajax',{},function(r){reservations=r.list||[];renderReservations();});}
function renderReservations(){var h='';$.each(reservations,function(_,r){h+='<tr><td>'+esc(r.resourceNm)+'</td><td>'+esc(r.rsvTitle)+'</td><td>'+esc(r.bizNm||'-')+'</td><td>'+esc(r.bgngDt)+'</td><td>'+esc(r.endDt)+'</td><td><button class="ds-mini-btn" onclick="editReservation('+r.reservationSn+')">수정</button> <button class="ds-mini-btn ds-mini-btn-danger" onclick="deleteReservation('+r.reservationSn+')">취소</button></td></tr>';});$('#reservationBody').html(h||'<tr><td colspan="6" class="ds-empty">예약 내역이 없습니다.</td></tr>');}
function toLocal(v){return (v||'').replace(' ','T');}
function editReservation(sn){var r=reservations.find(function(x){return String(x.reservationSn)===String(sn);});if(!r)return;$('#rsvSn').val(r.reservationSn);$('#rsvResource').val(r.resourceSn);$('#rsvBiz').val(r.bizId||'');$('#rsvTitle').val(r.rsvTitle);$('#rsvBegin').val(toLocal(r.bgngDt));$('#rsvEnd').val(toLocal(r.endDt));$('#rsvUseCn').val(rawText(r.useCn||''));window.scrollTo(0,0);}
function resetReservationForm(){$('#rsvSn,#rsvTitle,#rsvBegin,#rsvEnd,#rsvUseCn').val('');$('#rsvResource,#rsvBiz').val('');}
function saveReservation(){if(!$('#rsvResource').val()||!$('#rsvTitle').val().trim()||!$('#rsvBegin').val()||!$('#rsvEnd').val())return alert('자원, 예약명, 시작/종료일시는 필수입니다.');api('/resource/reservationSave.ajax',{reservationSn:$('#rsvSn').val(),resourceSn:$('#rsvResource').val(),bizId:$('#rsvBiz').val(),rsvTitle:$('#rsvTitle').val(),bgngDt:$('#rsvBegin').val().replace('T',' '),endDt:$('#rsvEnd').val().replace('T',' '),useCn:$('#rsvUseCn').val()},function(){resetReservationForm();loadReservations();});}
function deleteReservation(sn){if(!confirm('예약을 취소하시겠습니까? 캘린더 일정도 함께 삭제됩니다.'))return;api('/resource/reservationDelete.ajax',{reservationSn:sn},function(){resetReservationForm();loadReservations();});}
