var workRows=[],workBiz=[];
function wt(v){return window.decodeStoredText?window.decodeStoredText(v==null?'':v):(v==null?'':String(v))}
function wh(v){return $('<div>').text(wt(v)).html()}
function monday(d){d=new Date(d);var day=d.getDay()||7;d.setDate(d.getDate()-day+1);return d.toISOString().slice(0,10)}
function priorityText(n){return {1:'1 · 최우선',2:'2 · 높음',3:'3 · 보통',4:'4 · 낮음',5:'5 · 여유'}[n]||'3 · 보통'}
function statusText(s){return {WAIT:'대기',PROGRESS:'진행',DONE:'완료',CARRY:'이월'}[s]||s||'대기'}
function loadDaily(){var y=$('#workYmd').val()||new Date().toISOString().slice(0,10);$.getJSON(ctxPath+'/worklog/dailyList.ajax',{workYmd:y},function(r){workRows=r.list||[];workBiz=r.bizList||[];renderDaily()})}
function bizOptions(v){return '<option value="">공통/기타</option>'+workBiz.map(function(b){return '<option value="'+wh(b.bizId)+'" '+(String(v||'')===String(b.bizId)?'selected':'')+'>'+wh(b.bizAbrvNm||b.bizNm)+'</option>'}).join('')}
function priOptions(v){var h='';for(var i=1;i<=5;i++)h+='<option value="'+i+'" '+(Number(v||3)===i?'selected':'')+'>'+priorityText(i)+'</option>';return h}
function renderDaily(){var html=workRows.map(function(x){var isNew=!x.workItemSn;var overdue=x.exptEndYmd&&$('#workYmd').val()>x.exptEndYmd&&x.prgrsSttsCd!=='DONE';return '<article class="ds-worklog-item" data-sn="'+(x.workItemSn||'')+'" data-start="'+wh(x.taskBgngYmd||$('#workYmd').val())+'">'
+'<div class="ds-worklog-item-head"><div><span class="ds-worklog-kicker">'+(isNew?'신규 업무':'업무 · 시작 '+wh(x.taskBgngYmd||''))+'</span><strong>'+wh(x.workCn||'업무내용을 입력하세요.')+'</strong></div><span class="ds-worklog-priority-pill">'+wh(priorityText(x.priorityNo||3))+'</span></div>'
+'<div class="ds-worklog-meta-grid">'
+'<div class="ds-field"><label>프로젝트</label><select class="ds-select wi-biz">'+bizOptions(x.bizId)+'</select></div>'
+'<div class="ds-field"><label>우선순위</label><select class="ds-select wi-priority">'+priOptions(x.priorityNo)+'</select></div>'
+'<div class="ds-field"><label>업무구분</label><select class="ds-select wi-se"><option value="TASK">업무</option><option value="MEETING">회의</option><option value="SUPPORT">지원</option><option value="ETC">기타</option></select></div>'
+'<div class="ds-field"><label>상태</label><select class="ds-select wi-status"><option value="WAIT">대기</option><option value="PROGRESS">진행</option><option value="DONE">완료</option><option value="CARRY">이월</option></select></div>'
+'<div class="ds-field"><label>진행률(%)</label><input type="number" min="0" max="100" class="ds-input wi-rate" value="'+wh(x.prgrsRt==null?0:x.prgrsRt)+'"></div>'
+'<div class="ds-field"><label>예상완료일'+(overdue?' <span class="text-red-400">지연</span>':'')+'</label><input type="date" class="ds-input wi-end" value="'+wh(x.exptEndYmd||$('#workYmd').val())+'"></div></div>'
+'<div class="ds-worklog-content-grid"><div class="ds-field ds-worklog-main-content"><label>업무내용</label><textarea class="ds-textarea wi-cn" rows="4" placeholder="해야 할 업무와 범위를 구체적으로 적어주세요.">'+wh(x.workCn||'')+'</textarea></div>'
+'<div class="ds-field"><label>이슈·특이사항</label><textarea class="ds-textarea wi-issue" rows="3" placeholder="진행 중 발생한 이슈, 의사결정 필요사항 등을 적어주세요.">'+wh(x.issueCn||'')+'</textarea></div>'
+'<div class="ds-field"><label>익일/차주계획</label><textarea class="ds-textarea wi-next" rows="3" placeholder="다음 진행 계획이나 후속 작업을 적어주세요.">'+wh(x.nextPlanCn||'')+'</textarea></div></div>'
+'<div class="ds-worklog-actions">'+(isNew?'<button type="button" class="ds-btn ds-btn-outline" onclick="cancelNewWork()">취소</button>':'')+'<button type="button" class="ds-btn ds-btn-primary" onclick="saveWork(this)">저장</button>'+(isNew?'':'<button type="button" class="ds-btn ds-btn-outline" onclick="deleteWork(this)">삭제</button>')+'</div></article>'}).join('');$('#dailyRows').html(html||'<div class="ds-empty">등록된 일일 계획이 없습니다. 업무 추가를 눌러 시작하세요.</div>');$('#dailyRows article').each(function(i){var x=workRows[i]||{};$(this).find('.wi-se').val(x.workSeCd||'TASK');$(this).find('.wi-status').val(x.prgrsSttsCd||'WAIT')})}
function addRow(){var existing=workRows.some(function(x){return !x.workItemSn});if(existing){var el=$('#dailyRows article[data-sn=""]').get(0);if(el)el.scrollIntoView({behavior:'smooth',block:'center'});return}workRows.unshift({workSeCd:'TASK',prgrsSttsCd:'WAIT',prgrsRt:0,priorityNo:3,exptEndYmd:$('#workYmd').val()});renderDaily();var el=$('#dailyRows article').get(0);if(el)el.scrollIntoView({behavior:'smooth',block:'center'})}
function cancelNewWork(){workRows=workRows.filter(function(x){return !!x.workItemSn});renderDaily()}
function saveWork(btn){var a=$(btn).closest('article');var data={workItemSn:a.data('sn')||'',workYmd:$('#workYmd').val(),taskBgngYmd:a.attr('data-start'),bizId:a.find('.wi-biz').val(),priorityNo:a.find('.wi-priority').val(),exptEndYmd:a.find('.wi-end').val(),workSeCd:a.find('.wi-se').val(),workCn:a.find('.wi-cn').val(),prgrsSttsCd:a.find('.wi-status').val(),prgrsRt:a.find('.wi-rate').val(),issueCn:a.find('.wi-issue').val(),nextPlanCn:a.find('.wi-next').val()};if(!String(data.workCn||'').trim())return alert('업무내용을 입력하십시오.');$.post(ctxPath+'/worklog/dailySave.ajax',data,function(r){if(r.result==='OK')loadDaily();else alert(r.msg||'저장 실패')},'json')}
function deleteWork(btn){if(!confirm('이 업무를 삭제하시겠습니까?'))return;var sn=$(btn).closest('article').data('sn');$.post(ctxPath+'/worklog/dailyDelete.ajax',{workItemSn:sn},function(r){if(r.result==='OK')loadDaily();else alert('삭제 실패')},'json')}
function loadWeekly(){var w=$('#weekStart').val()||monday(new Date());$.getJSON(ctxPath+'/worklog/weeklyList.ajax',{weekStart:w},function(r){var groups={};(r.list||[]).forEach(function(x){var k=x.bizAbrvNm||x.bizNm||'공통/기타';(groups[k]=groups[k]||[]).push(x)});$('#weeklyRows').html(Object.keys(groups).map(function(k){return '<section class="border border-brand-border rounded-xl overflow-hidden"><div class="p-3 bg-slate-950/50 font-bold text-cyan-200">'+wh(k)+'</div>'+groups[k].map(function(x){return '<div class="p-3 border-t border-brand-border/60 grid grid-cols-12 gap-2"><span class="col-span-2 text-xs text-gray-400">'+wh(x.workYmd)+' · P'+wh(x.priorityNo||3)+'</span><strong class="col-span-4 ds-worklog-weekly-text">'+wh(x.workCn)+'</strong><span class="col-span-2">'+wh(statusText(x.prgrsSttsCd))+' '+wh(x.prgrsRt||0)+'%</span><span class="col-span-2 text-xs text-gray-400">예상 '+wh(x.exptEndYmd||'-')+'</span><span class="col-span-2 text-sm text-gray-400 ds-worklog-weekly-text">'+wh(x.nextPlanCn||'')+'</span></div>'}).join('')+'</section>'}).join('')||'<div class="ds-empty">해당 주간 업무가 없습니다.</div>')})}
function downloadWeekly(){location.href=ctxPath+'/worklog/weeklyExcel.do?weekStart='+encodeURIComponent($('#weekStart').val()||monday(new Date()))}
$(function(){if($('#workYmd').length){$('#workYmd').val(new Date().toISOString().slice(0,10));$('#workYmd').on('change',loadDaily);loadDaily()}if($('#weekStart').length){$('#weekStart').val(monday(new Date()));loadWeekly()}});
