package kr.co.TRSolution.trsIbp.worklog.web;

import java.time.LocalDate; import java.time.format.DateTimeFormatter; import java.util.List; import javax.annotation.Resource; import javax.servlet.http.HttpServletRequest; import javax.servlet.http.HttpServletResponse;
import org.apache.poi.ss.usermodel.Cell; import org.apache.poi.ss.usermodel.CellStyle; import org.apache.poi.ss.usermodel.Font; import org.apache.poi.ss.usermodel.IndexedColors; import org.apache.poi.ss.usermodel.Row; import org.apache.poi.ss.usermodel.Sheet; import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Controller; import org.springframework.web.util.HtmlUtils; import org.springframework.web.bind.annotation.RequestMapping; import org.springframework.web.bind.annotation.RequestMethod; import org.springframework.web.bind.annotation.RequestParam; import org.springframework.web.servlet.ModelAndView;
import kr.co.TRSolution.trsIbp.user.vo.UserVO; import kr.co.TRSolution.trsIbp.worklog.service.WorklogService; import kr.co.TRSolution.trsIbp.worklog.vo.WorklogVO;

@Controller public class WorklogController {
 @Resource(name="worklogService") private WorklogService s;
 @RequestMapping("/worklog/dailyList.do") public String daily(){return "/worklog/dailyList";}
 @RequestMapping("/worklog/weeklyReport.do") public String weekly(){return "/worklog/weeklyReport";}
 @RequestMapping("/worklog/dailyList.ajax") public ModelAndView list(WorklogVO v,HttpServletRequest r){UserVO u=login(r);bind(v,u);if(v.getWorkYmd()==null||v.getWorkYmd().isEmpty())v.setWorkYmd(LocalDate.now().toString());ModelAndView m=j();m.addObject("list",s.selectDailyList(v));m.addObject("bizList",s.selectBizList(v));m.addObject("result","OK");return m;}
 @RequestMapping(value="/worklog/dailySave.ajax",method=RequestMethod.POST) public ModelAndView save(WorklogVO v,HttpServletRequest r){ModelAndView m=j();try{UserVO u=login(r);bind(v,u);v.setRgtrId(u.getUserId());v.setMdfrId(u.getUserId());s.saveDaily(v);m.addObject("result","OK");m.addObject("workItemSn",v.getWorkItemSn());}catch(Exception e){m.addObject("result","FAIL");m.addObject("msg",e.getMessage());}return m;}
 @RequestMapping(value="/worklog/dailyDelete.ajax",method=RequestMethod.POST) public ModelAndView del(WorklogVO v,HttpServletRequest r){UserVO u=login(r);bind(v,u);v.setMdfrId(u.getUserId());ModelAndView m=j();m.addObject("result",s.deleteDaily(v)>0?"OK":"FAIL");return m;}
 @RequestMapping("/worklog/weeklyList.ajax") public ModelAndView weeklyList(WorklogVO v,@RequestParam(value="weekStart",required=false)String ws,HttpServletRequest r){UserVO u=login(r);bind(v,u);LocalDate start=weekStart(ws);v.setsDate(start.toString());v.seteDate(start.plusDays(4).toString());ModelAndView m=j();m.addObject("list",s.selectWeeklyList(v));m.addObject("weekStart",start.toString());m.addObject("weekEnd",start.plusDays(4).toString());m.addObject("result","OK");return m;}
 @RequestMapping("/worklog/weeklyExcel.do") public void excel(WorklogVO v,@RequestParam(value="weekStart",required=false)String ws,HttpServletRequest r,HttpServletResponse resp)throws Exception{UserVO u=login(r);bind(v,u);LocalDate start=weekStart(ws);v.setsDate(start.toString());v.seteDate(start.plusDays(4).toString());List<WorklogVO> list=s.selectWeeklyList(v);XSSFWorkbook wb=new XSSFWorkbook();Sheet sh=wb.createSheet("주간보고("+start.format(DateTimeFormatter.ofPattern("MM.dd"))+")");buildExcel(wb,sh,list,start,u.getUserNm());resp.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");String fn=java.net.URLEncoder.encode("주간보고_"+start+".xlsx","UTF-8").replace("+","%20");resp.setHeader("Content-Disposition","attachment; filename*=UTF-8''"+fn);wb.write(resp.getOutputStream());wb.close();}
 private void buildExcel(XSSFWorkbook wb,Sheet sh,List<WorklogVO> list,LocalDate start,String userNm){CellStyle title=wb.createCellStyle();Font tf=wb.createFont();tf.setBold(true);tf.setFontHeightInPoints((short)18);title.setFont(tf);title.setAlignment(CellStyle.ALIGN_CENTER);CellStyle head=wb.createCellStyle();Font hf=wb.createFont();hf.setBold(true);head.setFont(hf);head.setAlignment(CellStyle.ALIGN_CENTER);head.setVerticalAlignment(CellStyle.VERTICAL_CENTER);head.setWrapText(true);head.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());head.setFillPattern(CellStyle.SOLID_FOREGROUND);CellStyle wrap=wb.createCellStyle();wrap.setWrapText(true);wrap.setVerticalAlignment(CellStyle.VERTICAL_TOP);Row t=sh.createRow(2);t.createCell(1).setCellValue("『 주간보고 』");t.getCell(1).setCellStyle(title);sh.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(2,2,1,10));Row meta=sh.createRow(4);meta.createCell(1).setCellValue("작성자");meta.createCell(2).setCellValue(userNm);meta.createCell(5).setCellValue("기간");meta.createCell(6).setCellValue(start+" ~ "+start.plusDays(4));Row h=sh.createRow(7);String[] hs={"번호","프로젝트명","업무일자","우선순위","예상완료일","금주 진행 사항","진행상태","진행률","이슈·특이사항","차주/익일 계획"};for(int i=0;i<hs.length;i++){Cell c=h.createCell(i+1);c.setCellValue(hs[i]);c.setCellStyle(head);}int row=8,no=1;for(WorklogVO x:list){Row rr=sh.createRow(row++);rr.setHeightInPoints(42);String biz=x.getBizAbrvNm()!=null&&!x.getBizAbrvNm().isEmpty()?x.getBizAbrvNm():x.getBizNm();if(biz==null||biz.isEmpty())biz="공통/기타";rr.createCell(1).setCellValue(no++);rr.createCell(2).setCellValue(biz);rr.createCell(3).setCellValue(x.getWorkYmd());rr.createCell(4).setCellValue(x.getPriorityNo()==null?3:x.getPriorityNo());rr.createCell(5).setCellValue(x.getExptEndYmd()==null?"":x.getExptEndYmd());rr.createCell(6).setCellValue(plain(x.getWorkCn()));rr.createCell(7).setCellValue(status(x.getPrgrsSttsCd()));rr.createCell(8).setCellValue(x.getPrgrsRt()==null?0:x.getPrgrsRt().doubleValue());rr.createCell(9).setCellValue(plain(x.getIssueCn()));rr.createCell(10).setCellValue(plain(x.getNextPlanCn()));for(int c=1;c<=10;c++)rr.getCell(c).setCellStyle(wrap);}int[] widths={7,25,13,10,13,48,12,10,30,30};for(int i=0;i<widths.length;i++)sh.setColumnWidth(i+1,widths[i]*256);sh.createFreezePane(0,8);}
 private String plain(String value){String decoded=value==null?"":value;for(int i=0;i<3;i++){String next=HtmlUtils.htmlUnescape(decoded);if(next.equals(decoded))break;decoded=next;}return decoded;}
 private String status(String c){if("DONE".equals(c))return"완료";if("PROGRESS".equals(c))return"진행";if("CARRY".equals(c))return"이월";return"대기";} private LocalDate weekStart(String v){LocalDate d=(v==null||v.isEmpty())?LocalDate.now():LocalDate.parse(v);return d.minusDays(d.getDayOfWeek().getValue()-1);} private void bind(WorklogVO v,UserVO u){v.setCoId(u.getCoId());v.setUserId(u.getUserId());} private UserVO login(HttpServletRequest r){UserVO u=(UserVO)r.getSession().getAttribute("login");if(u==null)throw new IllegalStateException("로그인이 필요합니다.");return u;} private ModelAndView j(){return new ModelAndView("jsonView");}
}
