package kr.co.TRSolution.trsIbp.comm;
import javax.annotation.Resource; import javax.servlet.http.*; import org.springframework.web.servlet.handler.HandlerInterceptorAdapter;
import kr.co.TRSolution.trsIbp.audit.mapper.UserActionLogMapper; import kr.co.TRSolution.trsIbp.audit.vo.UserActionLogVO; import kr.co.TRSolution.trsIbp.user.vo.UserVO;
public class UserActionLogInterceptor extends HandlerInterceptorAdapter {
 @Resource(name="userActionLogMapper") private UserActionLogMapper mapper;
 @Override public void afterCompletion(HttpServletRequest req,HttpServletResponse res,Object handler,Exception ex)throws Exception{
  if(ex!=null||res.getStatus()>=400)return; HttpSession session=req.getSession(false); if(session==null)return; UserVO u=(UserVO)session.getAttribute("login"); if(u==null)return;
  String uri=req.getRequestURI().substring(req.getContextPath().length()); String action=action(uri,req); if(action==null)return;
  try{UserActionLogVO v=new UserActionLogVO();v.setCoId(u.getCoId());v.setUserId(u.getUserId());v.setActionSeCd(action);v.setMenuNm(menu(uri));v.setTargetId(target(req));v.setRequestUri(uri);v.setClientIpAddr(ip(req));v.setActionCn(menu(uri)+" "+("REG".equals(action)?"등록":"MDFCN".equals(action)?"수정":"삭제"));mapper.insertUserActionLog(v);}catch(Exception ignore){}
 }
 private String action(String uri,HttpServletRequest r){String l=uri.toLowerCase(); if(l.contains("delete"))return "DEL"; if(l.contains("insert"))return "REG"; if(l.contains("update"))return "MDFCN"; if(l.contains("save")){String mode=r.getParameter("saveMode");if("insert".equalsIgnoreCase(mode))return "REG";if("update".equalsIgnoreCase(mode))return "MDFCN";String id=saveIdentifier(uri,r);return id==null||id.trim().isEmpty()||"0".equals(id.trim())?"REG":"MDFCN";} return null;}
 private String saveIdentifier(String uri,HttpServletRequest r){if(uri.endsWith("/expense/expenseSave.ajax"))return r.getParameter("claimSn");if(uri.endsWith("/worklog/dailySave.ajax"))return r.getParameter("workItemSn");if(uri.endsWith("/resource/resourceSave.ajax"))return r.getParameter("resourceSn");if(uri.endsWith("/resource/reservationSave.ajax"))return r.getParameter("reservationSn");if(uri.endsWith("/notice/noticeSave.ajax"))return r.getParameter("noticeSn");if(uri.endsWith("/schedule/scheduleSave.ajax"))return r.getParameter("schdlSn");if(uri.endsWith("/biz/cstSave.ajax"))return r.getParameter("bizCstSn");if(uri.endsWith("/biz/mnpwSave.ajax"))return r.getParameter("bizMnpwSn");if(uri.endsWith("/biz/schdlSave.ajax"))return r.getParameter("bizSchdlSn");if(uri.endsWith("/biz/bizSave.ajax"))return r.getParameter("bizId");return null;}
 private String target(HttpServletRequest r){String[] n={"bizId","claimSn","workItemSn","noticeSn","resourceSn","reservationSn","schdlSn","userId","deptId","bizCstSn","bizMnpwSn","bizSchdlSn","custSn"};for(String x:n){String v=r.getParameter(x);if(v!=null&&!v.trim().isEmpty())return x+"="+v;}return null;}
 private String menu(String uri){if(uri.startsWith("/biz/"))return "프로젝트/사업";if(uri.startsWith("/expense/"))return "비용청구";if(uri.startsWith("/worklog/"))return "개인업무";if(uri.startsWith("/notice/"))return "공지사항";if(uri.startsWith("/resource/"))return "자원관리/예약";if(uri.startsWith("/schedule/"))return "일정관리";if(uri.startsWith("/user/"))return "사용자관리";if(uri.startsWith("/dept/"))return "조직관리";if(uri.startsWith("/authority/"))return "권한관리";return uri;}
 private String ip(HttpServletRequest r){String x=r.getHeader("X-Forwarded-For");if(x!=null&&!x.trim().isEmpty())return x.split(",")[0].trim();x=r.getHeader("X-Real-IP");return x!=null&&!x.trim().isEmpty()?x:r.getRemoteAddr();}
}
