package kr.co.TRSolution.trsIbp.resource.service.impl;
import java.util.List; import javax.annotation.Resource; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import kr.co.TRSolution.trsIbp.resource.mapper.ResourceMapper; import kr.co.TRSolution.trsIbp.resource.service.ResourceService; import kr.co.TRSolution.trsIbp.resource.vo.ResourceVO;
@Service("resourceService") public class ResourceServiceImpl implements ResourceService {
 @Resource(name="resourceMapper") private ResourceMapper mapper;
 public List<ResourceVO> selectResourceList(ResourceVO vo){return mapper.selectResourceList(vo);} public ResourceVO selectResource(ResourceVO vo){return mapper.selectResource(vo);} public List<ResourceVO> selectReservationList(ResourceVO vo){return mapper.selectReservationList(vo);} public List<ResourceVO> selectAvailableBizList(ResourceVO vo){return mapper.selectAvailableBizList(vo);}
 @Transactional public void saveResource(ResourceVO vo){if(vo.getResourceSn()==null||vo.getResourceSn()==0){mapper.insertResource(vo);}else{if(mapper.updateResource(vo)==0)throw new IllegalArgumentException("수정할 자원을 찾을 수 없습니다.");} mapper.deleteResourceAttrs(vo.getResourceSn()); if(vo.getAttrText()!=null){int seq=1; for(String line:vo.getAttrText().split("\\r?\\n")){line=line.trim(); if(line.isEmpty())continue; int p=line.indexOf('='); if(p<1)continue; ResourceVO a=new ResourceVO(); a.setResourceSn(vo.getResourceSn()); a.setResourceNm(line.substring(0,p).trim()); a.setResourceExpln(line.substring(p+1).trim()); a.setSortSeq(seq++); mapper.insertResourceAttr(a);}}}
 @Transactional public void deleteResource(ResourceVO vo){if(mapper.deleteResource(vo)==0)throw new IllegalArgumentException("삭제할 자원을 찾을 수 없습니다.");}
 @Transactional public void saveReservation(ResourceVO vo){if(vo.getBgngDt()==null||vo.getEndDt()==null||vo.getBgngDt().compareTo(vo.getEndDt())>=0)throw new IllegalArgumentException("예약 시작/종료시간을 확인하십시오."); if(mapper.selectOverlapCount(vo)>0)throw new IllegalStateException("해당 시간에 이미 예약된 자원입니다."); if(vo.getReservationSn()==null||vo.getReservationSn()==0){ mapper.insertSchedule(vo); mapper.insertScheduleUser(vo); mapper.insertReservation(vo); } else {ResourceVO old=mapper.selectReservation(vo); if(old==null)throw new IllegalArgumentException("예약정보를 찾을 수 없습니다."); vo.setSchdlSn(old.getSchdlSn()); mapper.updateSchedule(vo); if(mapper.updateReservation(vo)==0)throw new IllegalArgumentException("수정할 예약을 찾을 수 없습니다.");}}
 @Transactional public void deleteReservation(ResourceVO vo){ResourceVO old=mapper.selectReservation(vo); if(old==null)throw new IllegalArgumentException("예약정보를 찾을 수 없습니다."); vo.setSchdlSn(old.getSchdlSn()); mapper.deleteReservation(vo); mapper.deleteSchedule(vo);}
}
